# Global Configuration
timezone: 'Europe/Amsterdam'
permalink: '/:year/:month/:day/:title'
highlighter: null

# Custom Configuration
title: Elm Bark
tagline: barking mad about Elm
production_url: www.elmbark.com
